### ISSUE TITLE
image_to_string() crashes on lookup

### ISSUE THREAD

**Issue by twstagg** [klaxa/OCR-Manga#11]
» trohrt » [OCR-Manga]: ./Reader.py berserk.[mh].c001.cbz 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "./Reader.py", line 102, in lookup_entry
    string = self.image_to_dict(ocr_image)
  File "./Reader.py", line 273, in image_to_dict
    builder=pyocr.builders.TextBuilder(mode))
  File "./Reader.py", line 30, in image_to_string
    return self.tool.image_to_string(image, lang=lang,
AttributeError: 'Application' object has no attribute 'tool'

I'll take care of this

**Comment by klaxa** [comment]
This is the ConstMixin stuff, I blindly merged it. I should probably test these before merging.

**Comment by twstagg** [comment]
@klaxa Yup, I figured as much. Is there really any point in having globals separated to ConstMixin? Also, it would probably help to have people making the pull requests test their code before requesting...

On a side note, I'll probably spend a little time on cleanup here soon...

**Comment by klaxa** [comment]
I don't know, I don't really write really "pythonic" code, you'll have to ask @ewongbb.
