### ISSUE TITLE
ImportError: cannot import name 'ImageTk'

### ISSUE THREAD

**Issue by Dhs92** [klaxa/OCR-Manga#12]
dhs92@alex-mint ~/Desktop/Manga $ ./Reader.py ./Manga/Yotsubato!\ v01-12/Yotsubato!\ v01-02.rar 
Traceback (most recent call last):
  File "./Reader.py", line 3, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk'

**Comment by klaxa** [comment]
This isn't exactly an issue with OCR-Manga afaict. It looks like you are missing dependencies. Did you install tk correctly? (Mabye see: https://stackoverflow.com/questions/10630736/no-module-named-image-tk ?)

**Comment by Dhs92** [comment]
Huh, you're right. Seems the dependencies didn't install correctly. Thanks

**Comment by Dhs92** [comment]
Actually, scratch that
Doesn't seem to be working yet, even after installing

**Comment by klaxa** [comment]
So this can be closed then?

**Comment by CHAMOD** [comment]
I had the same problem.I solved it by upgrading pillow to the latest version.
