### ISSUE TITLE
frame 1X1 

### ISSUE THREAD

**Issue by omega16** [klaxa/OCR-Manga#19]
On Ubuntu 16.04 

The window doesn't appear. I mean that I can watch the window name but that's all , then I check part of code and find that the frame size  is 1x1 , so I added to my Reader.py :

if width==1 or height==1:
            width=100
            height=100

before line 135 to check and all works fine (I can see the window, image and  resize  without issues)

**Comment by klaxa** [comment]
Fixed by #20
